name: Lint and Test
description: Default CI action for self-assert

inputs:
  coverage:
    description: "Generate coverage report"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Lint
      run: npm run lint --if-present
      shell: bash

    - name: Test (with coverage)
      if: ${{ inputs.coverage != 'false' }}
      shell: bash
      run: npm test -- --coverage

    - name: Upload coverage report
      if: ${{ inputs.coverage != 'false' }}
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/

    - name: Test (without coverage)
      if: ${{ inputs.coverage == 'false' }}
      shell: bash
      run: npm test
