name: CI React extension

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["packages/react/**"]
  pull_request:
    branches: [main]
    paths: ["packages/react/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-version: ["18", "19"]

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "npm"

      - name: Install React ${{ matrix.react-version }}
        run: |
          npm rm react react-dom @types/react @types/react-dom --workspaces
          npm ci
          npm install react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }} \
            @types/react@${{ matrix.react-version }} @types/react-dom@${{ matrix.react-version }} \
            --save-dev --legacy-peer-deps

      - name: Test
        run: npm test -w packages/react
