name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-checks:
    name: Code checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - uses: ./.github/actions/code-checks

  update-pages:
    name: Update pages
    needs: run-checks
    if: ${{ github.ref_name == 'main' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:

      - name: Run docs workflow
        run: |
          gh workflow run publish.yml --repo self-assert/self-assert.github.io --ref feature/publish-artifact
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
    # permissions:
    #   contents: write
    # uses: self-assert/self-assert.github.io/.github/workflows/publish.yml@feature/publish-artifact
    # secrets:
    #   GH_PAT: ${{ secrets.GH_PAT }}
