on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: "Target branch"
        required: false
        default: "main"

  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release please
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
      debug_release: ${{ toJson(steps.release.outputs) }}

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.SELF_ASSERT_BOT_APP_ID }}
          private-key: ${{ secrets.SELF_ASSERT_BOT_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.generate-token.outputs.token }}
          target-branch: ${{ inputs.target-branch || 'main' }}

  publish:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.releases_created == 'true' }}
    strategy:
      matrix:
        package: ${{ fromJson(needs.release.outputs.paths_released) }}
    name: "Publish ${{ matrix.package }}"
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - uses: ./.github/actions/code-checks

      - name: Build package
        run: npm run build -w ${{ matrix.package }}

      - name: Publish package
        run: npm publish -w ${{ matrix.package }} --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  debug:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    env:
      RELEASE_CONTEXT: ${{ needs.release.outputs.debug_release }}
    steps:
      - run: echo "$RELEASE_CONTEXT"
