on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: "Target branch"
        required: false
        default: "main"

  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release please
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
      debug_release: ${{ toJson(steps.release.outputs) }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_PAT }}
          target-branch: ${{ inputs.target-branch || 'main' }}

  publish:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.releases_created == 'true' }}
    strategy:
      matrix:
        package: ${{ fromJson(needs.release.outputs.paths_released) }}
    name: "Publish ${{ matrix.package }}"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - uses: ./.github/actions/code-checks

      - name: Publish package
        run: npm publish --provenance --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  debug:
    needs: release
    runs-on: ubuntu-latest
    env:
      RELEASE_CONTEXT: ${{ toJson(needs.release.outputs.debug_release) }}
    steps:
      - run: echo "$RELEASE_CONTEXT"
